# This compose file simulates the locaweb hosting environment, with nginx 1.22.1 and php 8.3.0

services:
  nginx:
    image: nginx:1.22.1
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    #debug
    #command: 
    #  [nginx-debug, '-g', 'daemon off;']
  php:
    image: php:8.3.0-fpm
    volumes:
     - ./:/var/www/html