name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Append SMTP credentials to smtp.env
      shell: bash
      run: |
        echo "" >> smtp.env
        echo USERNAME=${{ secrets.SMTP_USERNAME }} >> smtp.env
        echo PASSWORD=${{ secrets.SMTP_PASSWORD }} >> smtp.env

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST1 }}
        user: ${{ secrets.USER1 }}
        password: ${{ secrets.PASS1 }}
        localDir: "."
        remoteDir: "public_html"