name: Deploy via ftp
on: push
env:
  smtp_username: ${{ secrets.SMTP_USERNAME }}
  smtp_password: ${{ secrets.SMTP_PASSWORD }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST1 }}
        user: ${{ secrets.USER1 }}
        password: ${{ secrets.PASS1 }}
        localDir: "."
        remoteDir: "public_html"
    
    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST2 }} 
        user: ${{ secrets.USER2 }}
        password: ${{ secrets.PASS2 }}
        localDir: "."
        remoteDir: "public_html"